apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankeurekaserver
  labels:
    app: bankeurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      service: bankeurekaserver
  template:
    metadata:
      labels:
        app: bankeurekaserver
        service: bankeurekaserver
    spec:
      containers:
        - name: bankeurekaserver
          image: bankeurekaserver.azurecr.io/bankeurekaserver:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8761
            - name: WebApiBaseAddress
              value: http://webapi