apiVersion: v1
kind: Service
metadata:
  name: bankeurekaserver
  labels:
    app: bankeurekaserver
    service: bankeurekaserver
spec:
  type: LoadBalancer
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    service: bankeurekaserver